// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SendEmail(arg1, arg2, arg3) {
  return window['go']['main']['App']['SendEmail'](arg1, arg2, arg3);
}

export function UpdateEmailSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateEmailSettings'](arg1, arg2, arg3, arg4);
}
